### ISSUE TITLE
ST20 wizard does not display "price per token" when using ETH or BTC as input

### ISSUE THREAD

**Issue by Deep-Meditation** [PolymathNetwork/polymath-website#1]
**Steps to reproduce** 

- Start ST20 wizard at https://www.polymath.network/wizard

- Enter 'Price per token' in BTC or ETH
![pricepertoken_btc](https://user-images.githubusercontent.com/13892117/39408975-94e1c1c2-4bac-11e8-95f6-0e6772186dcb.png)

- Confirm details(#27) section of wizard does not display price per token as inputted by the user

![confirm_details](https://user-images.githubusercontent.com/13892117/39408977-9aed47e4-4bac-11e8-9ff5-81adeb45de97.png)

-Issue is reproducible when using ETH instead of BTC as well.

**Comment by sajclarke** [comment]
Closing because issue is inactive and outdated
