### ISSUE TITLE
Inadequate Jurisdiction Options on Submission page

### ISSUE THREAD

**Issue by F-OBrien** [PolymathNetwork/polymath-website#41]
The Submission page does not include options to cover all Jurisdictions. Either more options should be added or an "Other" options should be added to avoid confusion. Issuers may believe this is part of the token creation process and so do not want to select options which are not correct for them.

Issue highlighted by a user on Telegram

![image](https://user-images.githubusercontent.com/42175565/56749236-3e927480-6779-11e9-975b-46d5451c1e06.png)

**Comment by Git-R-Goin** [comment]
Hi @F-OBrien 
I'd like to work on your project.

**Comment by Git-R-Goin** [comment]
Here's my email address kinjitakabe@yahoo.com
Hope to discuss the detail.

**Comment by sajclarke** [comment]
Thanks @F-OBrien this issue is now resolved
